title: lukia
description: bz
url: "https://lukia00.github.io"
lang: ko
timezone: Asia/Seoul
remote_theme: knhash/jekyllBear@e9fc243
github_username: lukia00

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      tags: [all]
  - scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/

Blog: /blog

exclude:
  - bin
  - README.md
